<?xml version="1.0" encoding="UTF-8"?>
<definitions
        xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
        xmlns:wsp="http://www.w3.org/ns/ws-policy"
        xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
        xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:tns="http://soap.trainticket.hccis.ca/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        targetNamespace="http://soap.trainticket.hccis.ca/"
        name="TrainTicketServiceImplService">

    <types>
        <xsd:schema>
            <xsd:import
                    namespace="http://soap.trainticket.hccis.ca/"
                    schemaLocation="http://10.4.33.51:8083/trainticketservice?xsd=1"/>
        </xsd:schema>
    </types>

    <!-- Messages -->
    <message name="getTickets">
        <part name="parameters" element="tns:getTickets"/>
    </message>

    <message name="getTicketsResponse">
        <part name="parameters" element="tns:getTicketsResponse"/>
    </message>

    <!-- Port type -->
    <portType name="TrainTicketService">
        <operation name="getTickets">
            <input
                    wsam:Action="http://soap.trainticket.hccis.ca/TrainTicketService/getTicketsRequest"
                    message="tns:getTickets"/>
            <output
                    wsam:Action="http://soap.trainticket.hccis.ca/TrainTicketService/getTicketsResponse"
                    message="tns:getTicketsResponse"/>
        </operation>
    </portType>

    <!-- Binding -->
    <binding name="TrainTicketServiceImplPortBinding" type="tns:TrainTicketService">
        <soap:binding
                transport="http://schemas.xmlsoap.org/soap/http"
                style="document"/>
        <operation name="getTickets">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <!-- Service -->
    <service name="TrainTicketServiceImplService">
        <port
                name="TrainTicketServiceImplPort"
                binding="tns:TrainTicketServiceImplPortBinding">
            <soap:address location="http://10.4.33.51:8083/trainticketservice"/>
        </port>
    </service>

</definitions>
